### ISSUE TITLE
Module doesnt check for each meta-key

### ISSUE THREAD

**Issue by gohabereg** [codex-team/codex.shortcuts#2]
Steps:
1. Register new shotcut for example `CMD+Z` and `() => console.log('CMD+Z')` as handler
2. On the page use the shortcut `CMD+SHIFT+Z`

Expected: nothing should happened because registered shortcut is `CMD+Z`, not `CMD+SHIFT+Z`
Actual: Handler is fired

**Comment by khaydarov** [comment]
closes #4
